//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountDetail
    {
        public accountDetail()
        {
            this.transactionDetails = new HashSet<transactionDetail>();
            this.transactionDetails1 = new HashSet<transactionDetail>();
        }
    
        public long accountNumber { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> editedDate { get; set; }
        public string accountStatus { get; set; }
        public Nullable<System.DateTime> closingDate { get; set; }
        public Nullable<long> accountBalance { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public string accountType { get; set; }
        public Nullable<int> userId { get; set; }
        public string type { get; set; }
    
        public virtual accountTypeDetail accountTypeDetail { get; set; }
        public virtual ICollection<transactionDetail> transactionDetails { get; set; }
        public virtual ICollection<transactionDetail> transactionDetails1 { get; set; }
        public virtual userDetail userDetail { get; set; }
    }
}
