//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountTypeDetail
    {
        public accountTypeDetail()
        {
            this.accountDetails = new HashSet<accountDetail>();
        }
    
        public string accountType { get; set; }
        public Nullable<long> lowerBound { get; set; }
        public Nullable<long> upperBound { get; set; }
    
        public virtual ICollection<accountDetail> accountDetails { get; set; }
    }
}
