//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branchDetail
    {
        public branchDetail()
        {
            this.userDetails = new HashSet<userDetail>();
        }
    
        public string branchId { get; set; }
        public string branchName { get; set; }
        public Nullable<int> assigned { get; set; }
    
        public virtual ICollection<userDetail> userDetails { get; set; }
    }
}
