//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginDetail
    {
        public loginDetail()
        {
            this.userDetails = new HashSet<userDetail>();
        }
    
        public string loginId { get; set; }
        public string loginPassword { get; set; }
        public string userRole { get; set; }
    
        public virtual ICollection<userDetail> userDetails { get; set; }
    }
}
