//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionDetail
    {
        public long transactionId { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string transactionType { get; set; }
        public Nullable<int> transactionAuthorizedBy { get; set; }
        public Nullable<long> sourceAccountNumber { get; set; }
        public Nullable<long> destinationAccountNumber { get; set; }
        public Nullable<int> transactionAmount { get; set; }
        public string comments { get; set; }
    
        public virtual accountDetail accountDetail { get; set; }
        public virtual accountDetail accountDetail1 { get; set; }
    }
}
